version: "3.9"
services:
  database:
    image: postgres:14.1-alpine
    container_name: backbase_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backbase_db
      TZ: Europe/Warsaw
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: