logging:
  level:
    root: INFO
spring:
  app:
    name: BackBaseApp
    client:
      omdb:
        url: http://www.omdbapi.com
        key: ${OMDB_API_KEY}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      leak-detection-threshold: 18000
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 10000
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false
  properties:
    hibernate:
      jdbc:
        time_zone: Europe/Warsaw
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
    out-of-order: false

memcached:
  cache:
    servers: ${MEMCACHE_URL}:${MEMCACHE_PORT}
    prefix: ${spring.app.name}
    expiration: 86400 #in sec 24h
    operation-timeout: 500
    provider: static
